on:
  pull_request:
    branches:
    - main

jobs:
  check-commit-count:
    name: Check Commit Count
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          package.json
        sparse-checkout-cone-mode: false
    - name: Count
      run: | 
        git rev-list HEAD --count
        echo $COUNT
