on:
  pull_request:
    branches:
    - main


  
jobs:
  check-if-is-libui-on-develop:     
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          package.json
        sparse-checkout-cone-mode: false
    - name: Get Branch
      run: | 
        LIB_UI_BRANCH=$(cat ./package.json | jq '.dependencies["anef-ui"]' | tr -d '"')
        echo $LIB_UI_BRANCH
        if [ $LIB_UI_BRANCH != "ssh://github.com:MI-ANEF/anef-ui-lib.git#develop" ]
        then
          echo La branche Lib UI n'est pas sur develop
          exit 1
        fi
        echo LA branche Lib UI branch est sur develop

