on:
  pull_request:
    branches:
    - main
jobs:
  check-if-is-libui-on-develop:
    runs-on: ubuntu-latest
    env: 
      PACKAGE_VERSION: ""
    steps: 
      - run: PACKAGE_VERSION=$(cat /package.json | jq '.version' | tr -d '"')
      - run: echo PACKAGE_VERSION
