on:
  pull_request:
    branches:
    - main

env: 
  LIB_UI_BRANCH: ""
  
jobs:
  check-if-is-libui-on-develop:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          package.json
        sparse-checkout-cone-mode: false
    - name: Get Branch
      run: | 
        LIB_UI_BRANCH=$(cat ./package.json | jq '.dependencies["anef-ui"]' | tr -d '"')
        echo $LIB_UI_BRANCH
    - name: Test
      if: LIB_UI_BRANCH != "ssh://github.com:MI-ANEF/anef-ui-lib.git#develop"
      run: exit 1
    - name: Pass
      run: echo Lib UI branch is on develop

